//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcExample.HostFactoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HostFactoryService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetServiceInfo", ReplyAction="http://tempuri.org/IService/GetServiceInfoResponse")]
        MvcExample.HostFactoryService.GetServiceInfoResponse GetServiceInfo(MvcExample.HostFactoryService.GetServiceInfoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetServiceInfo", ReplyAction="http://tempuri.org/IService/GetServiceInfoResponse")]
        System.Threading.Tasks.Task<MvcExample.HostFactoryService.GetServiceInfoResponse> GetServiceInfoAsync(MvcExample.HostFactoryService.GetServiceInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceInfoRequest {
        
        public GetServiceInfoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetServiceInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid DependencyInstanceId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ServiceImplementationTypeName;
        
        public GetServiceInfoResponse() {
        }
        
        public GetServiceInfoResponse(System.Guid DependencyInstanceId, string ServiceImplementationTypeName) {
            this.DependencyInstanceId = DependencyInstanceId;
            this.ServiceImplementationTypeName = ServiceImplementationTypeName;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : MvcExample.HostFactoryService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<MvcExample.HostFactoryService.IService>, MvcExample.HostFactoryService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcExample.HostFactoryService.GetServiceInfoResponse MvcExample.HostFactoryService.IService.GetServiceInfo(MvcExample.HostFactoryService.GetServiceInfoRequest request) {
            return base.Channel.GetServiceInfo(request);
        }
        
        public System.Guid GetServiceInfo(out string ServiceImplementationTypeName) {
            MvcExample.HostFactoryService.GetServiceInfoRequest inValue = new MvcExample.HostFactoryService.GetServiceInfoRequest();
            MvcExample.HostFactoryService.GetServiceInfoResponse retVal = ((MvcExample.HostFactoryService.IService)(this)).GetServiceInfo(inValue);
            ServiceImplementationTypeName = retVal.ServiceImplementationTypeName;
            return retVal.DependencyInstanceId;
        }
        
        public System.Threading.Tasks.Task<MvcExample.HostFactoryService.GetServiceInfoResponse> GetServiceInfoAsync(MvcExample.HostFactoryService.GetServiceInfoRequest request) {
            return base.Channel.GetServiceInfoAsync(request);
        }
    }
}
